// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT_lNX2S5KZbVlVGqA4TO-AERjey2aAJE',
    appId: '1:857766700318:web:75cb39daefdc7314e0d50f',
    messagingSenderId: '857766700318',
    projectId: 'medifest-367e9',
    authDomain: 'medifest-367e9.firebaseapp.com',
    storageBucket: 'medifest-367e9.appspot.com',
    measurementId: 'G-WW803LKV8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyBm10Ewfie4Cn69tW-_Oy-ImIO8Re78U',
    appId: '1:857766700318:android:dd713129ec34c25ee0d50f',
    messagingSenderId: '857766700318',
    projectId: 'medifest-367e9',
    storageBucket: 'medifest-367e9.appspot.com',
  );
}
